<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Invoice;
use App\Models\User;
use App\Models\SchoolClass;
use App\Models\SchoolSession;
use Carbon\Carbon;

class InvoiceSeeder extends Seeder
{
    public function run(): void
    {
        $student = User::where('role', 'student')->first();
        $class = SchoolClass::first();
        $session = SchoolSession::first();

        if ($student && $session) {
            Invoice::firstOrCreate([
                'student_id' => $student->id,
                'session_id' => $session->id,
                'title' => 'Tuition Fee',
            ], [
                'class_id' => $class ? $class->id : null,
                'amount' => 120.50,
                'status' => 'unpaid',
                'due_date' => Carbon::now()->addDays(10),
                'notes' => 'Generated by InvoiceSeeder for testing.',
            ]);
        }
    }
}
