<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Invoice;
use App\Models\User;
use App\Models\SchoolClass;
use App\Models\SchoolSession;
use Carbon\Carbon;
use Illuminate\Support\Facades\Schema;

class InvoiceSeeder extends Seeder
{
    public function run(): void
    {
        // ✅ Student (يدعم role column أو Spatie hasRole)
        $student = User::query()
            ->when(Schema::hasColumn('users', 'role'), function ($q) {
                $q->where('role', 'student');
            })
            ->first();

        if (!$student) {
            $student = User::all()->first(function ($u) {
                return method_exists($u, 'hasRole') && $u->hasRole('student');
            });
        }

        // ✅ Session (يفضل latest)
        $session = SchoolSession::latest()->first() ?: SchoolSession::first();

        // ✅ Class (يفضل من نفس session لو عندك session_id في school_classes)
        $class = null;
        if ($session && Schema::hasColumn('school_classes', 'session_id')) {
            $class = SchoolClass::where('session_id', $session->id)->first();
        }
        $class = $class ?: SchoolClass::first();

        if (!$student || !$session) {
            return;
        }

        // ✅ جهّز بيانات الفاتورة حسب الأعمدة الموجودة
        $createData = [
            'student_id' => $student->id,
            'session_id' => $session->id,
            'title'      => 'Tuition Fee',
        ];

        $extraData = [
            'amount'   => 120.50,
            'status'   => 'unpaid',
            'due_date' => Carbon::now()->addDays(10),
        ];

        // ✅ class_id لو موجود
        if (Schema::hasColumn('invoices', 'class_id')) {
            $extraData['class_id'] = $class ? $class->id : null;
        }

        // ✅ paid_amount لو موجود (الكود الجديد يعتمد عليه)
        if (Schema::hasColumn('invoices', 'paid_amount')) {
            $extraData['paid_amount'] = 0;
        }

        // ✅ invoice_number لو موجود (لو ما عندك auto-generate)
        if (Schema::hasColumn('invoices', 'invoice_number')) {
            $extraData['invoice_number'] = 'INV-' . Carbon::now()->format('Ymd') . '-' . rand(1000, 9999);
        }

        // ✅ notes لو موجود
        if (Schema::hasColumn('invoices', 'notes')) {
            $extraData['notes'] = 'Generated by InvoiceSeeder for testing.';
        }

        Invoice::firstOrCreate($createData, $extraData);
    }
}
