<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\User;

class StudentAcademicInfoSeeder extends Seeder
{
    public function run(): void
    {
        $students = User::where('role', 'student')->get();

        if ($students->isEmpty()) {
            $this->command->warn('⚠️ لا يوجد طلاب — شغّل UserSeeder أولاً.');
            return;
        }

        $columns = Schema::getColumnListing('student_academic_infos');
        $now = now();
        $count = 0;

        foreach ($students as $student) {
            $data = [
                'student_id'      => $student->id,
                'board_reg_no'    => 'REG-' . str_pad($student->id, 5, '0', STR_PAD_LEFT),
                'admission_no'    => 'ADM-' . $student->id,
                'roll_no'         => rand(1, 500),
                'admission_date'  => $now->copy()->subMonths(rand(1, 12))->toDateString(),
                'session_id'      => $student->session_id ?? 1,
                'remarks'         => 'Generated by StudentAcademicInfoSeeder',
                'created_at'      => $now,
                'updated_at'      => $now,
            ];

            // فلترة الأعمدة الموجودة في الجدول
            $filtered = array_intersect_key($data, array_flip($columns));

            DB::table('student_academic_infos')->updateOrInsert(
                ['student_id' => $student->id],
                $filtered
            );

            $count++;
        }

        $this->command->info("✅ StudentAcademicInfoSeeder: تم إنشاء/تحديث بيانات أكاديمية لـ {$count} طالب.");
    }
}
